---
version: '3'

services:
  postgres:
    image: postgres:13
    ports:
        - "5432:5432"
    environment:
      POSTGRES_USER: data
      POSTGRES_PASSWORD: data!secure
      POSTGRES_DB: data
    volumes:
      - postgres_data_container:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "data"]
      interval: 5s
      retries: 5
    restart: always

  arangodb:
    image: arangodb:latest
    environment:
      ARANGO_ROOT_PASSWORD: data!secure
    ports:
      - 8529:8529
    volumes:
      - arangodb_data_container:/var/lib/arangodb3
      - arangodb_apps_data_container:/var/lib/arangodb3-apps

  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: data!secure
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  redis:
    image: "redis:alpine"
    command: redis-server --requirepass data!secure
    ports:
      - "6379:6379"
    volumes:
      - redis_data_container:/var/lib/redis
      - redis_data_container:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master

  zookeeper:
    image: "bitnami/zookeeper:latest"
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:2.5.0
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

volumes:
  postgres_data_container:
  arangodb_data_container:
  arangodb_apps_data_container:
  mongodb_data_container:
  redis_data_container:
